### ISSUE TITLE
window.require is not a function

### ISSUE THREAD

**Issue by nihalar** [tkambler/electron-preferences#19]
I'm getting this error. The preference window opens but its just blank.

**Comment by davidsulpy** [comment]
Hey @nihalar you need to add the following to your constructor opts:

```
webPreferences: {
			nodeIntegration: true
		}
```

This is due to change in the electron framework behavior that doesn't default to allowing nodeIntegration on `BrowserWindow` objects. By setting, it will override the default behavior and allow the loading of node components inside the prefs
