### ISSUE TITLE
Selecting a different folder don't change the preference

### ISSUE THREAD

**Issue by tolbard** [tkambler/electron-preferences#21]
Hi,
after having selected a specific folder the path is not changed in the preferences object.

**Comment by jan-zajic** [comment]
Me too. Field of 'type': 'directory' doesn't work at all, because it cannot be changed ... (OS: Windows, version: 2.0.0)

**Comment by jan-zajic** [comment]
@tolbard I finally solved it! For others, the error is:
```
Uncaught TypeError: l.showOpenDialog(...).then is not a function
    at onClick (app.bundle.js:14)
    at Object.<anonymous> (app.bundle.js:22)
    at Object.invokeGuardedCallback (app.bundle.js:22)
    at Object.invokeGuardedCallbackAndCatchFirstError (app.bundle.js:22)
    at P (app.bundle.js:22)
    at R (app.bundle.js:22)
    at F (app.bundle.js:22)
    at T (app.bundle.js:22)
    at D (app.bundle.js:22)
    at B (app.bundle.js:22)
```
and it means that you (in project where you used electron-preferences library) have dependency on electron older than 6.0.0.  Before version 6, dialog.showOpenDialog() returns a String[] rather than a Promise<Object>. If i upgraded my project to 6 major version of Electron framework, directory component works just fine.

So fix for this issue is just add mention to README.md that electron-preferences require electron framework version 6 or newer..

**Comment by pvrobays** [comment]
Closing this issue.
Currently the lowest supported version by electron itself is 10.x.y.
